os:
  - linux
#  - osx

dist: trusty
sudo: required

language:
  - cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - libgtest-dev
    - liblua5.2-dev
    - zlib1g-dev
    - g++-5
    - gcc-5
    - clang-5.0
    - libc6:i386
    - lua5.1
    - libdbus-1-dev
    - build-essential
    - mercurial
    - make
    - cmake
    - autoconf
    - automake
    - libtool
    - libasound2-dev
    - libpulse-dev
    - libaudio-dev
    - libx11-dev
    - libxext-dev
    - libxrandr-dev
    - libxcursor-dev
    - libxi-dev
    - libxinerama-dev
    - libxxf86vm-dev
    - libxss-dev
    - libgl1-mesa-dev
    - libesd0-dev
    - libudev-dev
    - libgles1-mesa-dev
    - libgles2-mesa-dev
    - libegl1-mesa-dev
    - libibus-1.0-dev
    - libsdl2-dev
    - libsdl2-ttf-dev
    - libvorbis-dev
    - gettext
    - libtheora-dev
    - libjpeg-dev
    - libpng12-dev
    - libcurl4-openssl-dev
    - libsdl2-mixer-dev
    - libxml2-dev
    - libopenal-dev
    - p7zip-full
    - binutils-dev
    - libxvidcore-dev
    - libmxml-dev
    - libglib2.0-dev
    - libgtk2.0-dev
    - libgtkglext1-dev
    - libgtksourceview2.0-dev
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-5.0

script:
# On Linux, we turn on all the projects
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cmake -DUFOAI_BUILD_GAME=ON -DUFOAI_BUILD_UFO2MAP=ON -DUFOAI_BUILD_UFODED=ON -DUFOAI_BUILD_UFO=ON -DUFOAI_BUILD_UFOMODEL=ON -DUFOAI_BUILD_UFOSLICER=ON -DUFOAI_BUILD_UFORADIANT=ON -DUFOAI_BUILD_UFOTESTALL=ON && make; fi
#  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cmake -G Xcode && xcodebuild -list -project ufoai.xcodeproj && xcodebuild -project ufoai.xcodeproj -target ALL_BUILD | xcpretty -f `xcpretty-travis-formatter`; fi

#notifications:
#  email:

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" && export CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-5.0" && export CC="clang-5.0"; fi

install:
  - gem install xcpretty
  - gem install xcpretty-travis-formatter

cache: apt
